//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//namespace Inspec.Mercury.Workflow.Common.Components.Properties {
namespace Inspec.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inspec.Mercury.Workflow.Common.Components.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &apos;{0}&apos; resource could not be found that matched the exception code &apos;{1}&apos;. Ensure that there is an entry in the BusinessProcessExceptionMessages resource file for the resource..
        /// </summary>
        internal static string BpExceptionFactoryMissingResource {
            get {
                return ResourceManager.GetString("BpExceptionFactoryMissingResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find configuration value for rule &apos;{0}&apos;..
        /// </summary>
        internal static string BreValueDoesNotExist {
            get {
                return ResourceManager.GetString("BreValueDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in static constructor: {0}.
        /// </summary>
        internal static string ConfigManagerErrorCtor {
            get {
                return ResourceManager.GetString("ConfigManagerErrorCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading configuration: {0}.
        /// </summary>
        internal static string ConfigManagerErrorLoadingConfig {
            get {
                return ResourceManager.GetString("ConfigManagerErrorLoadingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.inspec.org/mercury/xsd/wkf/common/DacOutput/v1.
        /// </summary>
        internal static string DacDefaultOutputNamespace {
            get {
                return ResourceManager.GetString("DacDefaultOutputNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database type &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string DacInvalidDatabaseType {
            get {
                return ResourceManager.GetString("DacInvalidDatabaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of a stored procedure or a SQLstring must be specified..
        /// </summary>
        internal static string DacNoSpNameOrSqlString {
            get {
                return ResourceManager.GetString("DacNoSpNameOrSqlString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection string could not be found matching the database type &apos;{0}&apos; and environment &apos;{1}&apos;..
        /// </summary>
        internal static string DacNullConnectionString {
            get {
                return ResourceManager.GetString("DacNullConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string DacParametersNodeName {
            get {
                return ResourceManager.GetString("DacParametersNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResultSet.
        /// </summary>
        internal static string DacResultSetNodeName {
            get {
                return ResourceManager.GetString("DacResultSetNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReturnValue.
        /// </summary>
        internal static string DacReturnValueNodeName {
            get {
                return ResourceManager.GetString("DacReturnValueNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RetVal.
        /// </summary>
        internal static string DacReturnValueParamName {
            get {
                return ResourceManager.GetString("DacReturnValueParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A resource matching the key &apos;{0}&apos; could not be found when retrieving information about database user-defined types (UDTs). Ensure that there is an entry in the DatabaseUdt resource file for the resource..
        /// </summary>
        internal static string DatabaseUdtProcessingMissingResource {
            get {
                return ResourceManager.GetString("DatabaseUdtProcessingMissingResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ns0.
        /// </summary>
        internal static string DefaultBtsNamespacePrefix {
            get {
                return ResourceManager.GetString("DefaultBtsNamespacePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &apos;{0}&apos; resource could not be found that matched the email type &apos;{1}&apos;. Ensure that there is an entry in the EmailMessages resource file for the resource..
        /// </summary>
        internal static string EmailProcessingMissingResource {
            get {
                return ResourceManager.GetString("EmailProcessingMissingResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.inspec.org/mercury/xsd/fra/SoapFaultDetail/v1.
        /// </summary>
        internal static string ExProcessingSoapFaultDetailMsgNamespace {
            get {
                return ResourceManager.GetString("ExProcessingSoapFaultDetailMsgNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot append the nodes because the destination node identified by the XPath &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string MsgProcessingDestNodeInvalidXPath {
            get {
                return ResourceManager.GetString("MsgProcessingDestNodeInvalidXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.inspec.org/ideas/xsd/wkf/common/ProcessStartResponse/v1.
        /// </summary>
        internal static string MsgProcessingProcessStartResponseNamespace {
            get {
                return ResourceManager.GetString("MsgProcessingProcessStartResponseNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessStartResponse.
        /// </summary>
        internal static string MsgProcessingProcessStartResponseNodeName {
            get {
                return ResourceManager.GetString("MsgProcessingProcessStartResponseNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.inspec.org/mercury/xsd/wkf/common/variable/int/v1.
        /// </summary>
        internal static string MsgProcessingVarIntNamespace {
            get {
                return ResourceManager.GetString("MsgProcessingVarIntNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Int.
        /// </summary>
        internal static string MsgProcessingVarIntNodeName {
            get {
                return ResourceManager.GetString("MsgProcessingVarIntNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password specified for the security token is invalid..
        /// </summary>
        internal static string SecurityInvalidPassword {
            get {
                return ResourceManager.GetString("SecurityInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username specified for the security token is not valid..
        /// </summary>
        internal static string SecurityInvalidUsernameFormat {
            get {
                return ResourceManager.GetString("SecurityInvalidUsernameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A session for the user does not exist..
        /// </summary>
        internal static string SecuritySessionDoesNotExist {
            get {
                return ResourceManager.GetString("SecuritySessionDoesNotExist", resourceCulture);
            }
        }
    }
}
